# Copyright 2026 The PDFium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../pdfium.gni")
import("../../testing/test.gni")

source_set("png_codec") {
  testonly = true
  sources = [ "png_codec.h" ]
  deps = []

  if (pdf_use_skia) {
    sources += [ "png_codec_skia.cpp" ]
    deps += [ "//skia" ]
  } else {
    sources += [ "png_codec_libpng.cpp" ]
    deps += [
      "../../third_party:png",
      "../../third_party:zlib",
    ]
  }

  configs += [
    "../../:pdfium_strict_config",
    "../../:pdfium_noshorten_config",
  ]
  public_deps = [ "../../core/fxcrt" ]
}

pdfium_unittest_source_set("unittests") {
  sources = [ "png_codec_unittest.cpp" ]
  deps = [ ":png_codec" ]
  pdfium_root_dir = "../../"
}
